-- MySQL Script generated by MySQL Workbench
-- sáb 02 jun 2018 01:19:07 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FSI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FSI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FSI` DEFAULT CHARACTER SET utf8 ;
USE `FSI` ;

-- -----------------------------------------------------
-- Table `FSI`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FSI`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FSI`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FSI`.`Pedidos` (
  `idPedidos` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NOT NULL,
  `cliente` VARCHAR(45) NOT NULL,
  `producto` VARCHAR(45) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  ` Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedidos`, ` Clientes_idCliente`),
  INDEX `fk_Pedidos_ Clientes_idx` (` Clientes_idCliente` ASC),
  CONSTRAINT `fk_Pedidos_ Clientes`
    FOREIGN KEY (` Clientes_idCliente`)
    REFERENCES `FSI`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FSI`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FSI`.`Productos` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  `Pedidos_ Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `Pedidos_idPedidos`, `Pedidos_ Clientes_idCliente`),
  INDEX `fk_Productos_Pedidos1_idx` (`Pedidos_idPedidos` ASC, `Pedidos_ Clientes_idCliente` ASC),
  CONSTRAINT `fk_Productos_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos` , `Pedidos_ Clientes_idCliente`)
    REFERENCES `FSI`.`Pedidos` (`idPedidos` , ` Clientes_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
